<?php /* Smarty version Smarty-3.1.14, created on 2015-09-09 11:16:31
         compiled from ".\templates\display\past-projects.tpl.html" */ ?>
<?php /*%%SmartyHeaderCode:122655e5596c13b5c3-16859890%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'caaaa44eee69bfea79ed2c249df34b4074196db1' => 
    array (
      0 => '.\\templates\\display\\past-projects.tpl.html',
      1 => 1441786153,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '122655e5596c13b5c3-16859890',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.14',
  'unifunc' => 'content_55e5596c1654b6_13136871',
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_55e5596c1654b6_13136871')) {function content_55e5596c1654b6_13136871($_smarty_tpl) {?><div id="content" class="content-box-m">

  <h3>PAST  PROJECTS </h3>
<h4>A  longitudinal cohort study of HIV-infected persons hospitalized with pneumonia  in two settings: Mulago Hospital, Kampala and San Francisco General Hospital,  San Francisco</h4>
<p><i>Study  period:</i> October 2008  – December 2013. <i>Brief description:</i> Part of  the Lung HIV Study, a network of 8 research programs and a central data  coordinating center whose shared goal is to study the spectrum of  HIV-associated lung disease and create a specimen bank and accompanying  clinical database to catalyze future studies in the field. The MIND-IHOP study  evaluates the diagnosis and epidemiology of HIV-associated pulmonary infections  and the human responses to those infections. <i>Collaborators:</i> MU-UCSF Research Collaboration. <i>Sponsored by:</i> National Heart Lung and Blood Institute (NHLBI)</p>

<h4>U01  Mulago III Parish Cohort Study: Longitudinal comparison of antimalarial  treatment efficacy</h4>
<p><i>Study  period:</i> November 2004  to December 2008. <i>Brief description:</i> This randomized, single-blinded, longitudinal clinical trial was designed to  compare the safety, tolerability and efficacy of three different combination  antimalarial regimens for the treatment of uncomplicated malaria. The study  revealed that AL was superior to other anti-malarial combinations. <i>Collaborators:</i> MU-UCSF Research  Collaboration. <i>Sponsored by</i>: The  National Institutes of Health/Division of Microbiology and Infectious Diseases  (NIH/DMID) </p>
      
    <h4>Pharmacokinetics of Antimalarial  Medications in Ugandan Children</h4>
    <p> <i>Study period:</i> June 2007 to December 2008. <i>Brief description:</i> This study  investigated the pharmacology of artemether/lumefantrine and  artesunate/amodiaquine in HIV un-infected children in Kampala, Uganda.  The comparison to prior adult data suggests  that LR exposure is lower in children and that AQ/DEAQ exposure is similar in  children and adults.  For the artemisinin  drugs, differences between exposure in children and adults vary depending on  which artemisinin is administered. PK distinctions between children and adults  should be considered to optimize dosing strategies for these widely utilized  ACT regimens. <i>Collaborators:</i> MU-UCSF  Research Collaboration. <i>Sponsored by</i>:  CFAR, Drug Research Unit. (It is not clear whether the one who wrote this  summary was reviewing past data or actually presenting what our study found. It  needs to be edited by the author and he/she should include more of the  findings.)</p>
    
    <h4>CHAMP:  The Children with HIV and Malaria Project</h4>
    <p><i>Study  period: October </i>2005  to May 2009. <i>Brief description:</i> The  aim of this study was to study the interactions between Human Immunodeficiency  Virus (HIV) infection and malaria in African children.  CHAMP has led to several important  discoveries about malaria and HIV. In addition with such close clinical  follow-up, CHAMP has also provided an opportunity to better understand other  aspects of the disease HIV causes in African children. <i>Collaborators:</i> MU-UCSF Research Collaboration. <i>Sponsored by:</i>  National  Institute of Health (NIH)(Even for CHAMP, we need to list the &ldquo;several&rdquo;  important findings that we got.)</p>
    
      <h4>TB-VCT:  HIV Voluntary Counseling and Testing for TB Evaluation Patients and their  Family and Household Members in Kampala Uganda</h4>
      <p><i>Study  period:</i> August 2007  to March 2012. <i>Brief description:</i> The  project aimed to determine the uptake of and barriers to HIV VCT among TB  evaluation patients as well as comparing VCT uptake between Home-based VCT and  TB Clinic-based VCT for family and household members of TB evaluation patients.  This project has shown that it is feasible to carry HIV testing of households  of subjects at high risk of testing HIV positive in this resource limited  setting, although invariably showing that home HIV testing was superior to  clinic based HIV testing  for  successfully  testing household members.  Predictors of successful Household Testing were, testing at Home Vs Clinic  (aOR, 4.0, (1.6-6.2), higher household size and household member being female.  The highest yield of HIV positive among household members was a spouse of an  HIV positive TB evaluation subject. These results provide a working model of  TB/HIV VCT that could be rapidly implemented across sub-Saharan Africa given  the substantial pre-existing TB control infrastructure in the region. <i>Collaborators:</i> MU-UCSF Research Collaboration. <i>Sponsored by:</i> The National Institute  of Health (NIH)</p>
      
      <h4>FRESH-AIR:  The Impact of Household Ventilation on Transmission of Tuberculosis among  Household Contacts of Active Tuberculosis Patients in Kampala, Uganda</h4>
      <p><i>Study  period:</i> July 2010 to  December 2011. <i>Brief description:</i> This pilot study tested the feasibility of an in-home measurement of  ventilation using a carbon dioxide (CO2) tracer gas decay technique, a low cost  method, and evaluated if household ventilation is associated with TB in  household contacts of adults with pulmonary TB (PTB) in Uganda. Findings  indicated that Measuring household ventilation was feasible and Ventilation  rates were lower (although not statistically significant) in homes with versus  without co-prevalent TB in household contacts.<i> Collaborators:</i> MU-UCSF Research Collaboration. <i>Sponsored by:</i> UCSF Center for AIDS  Research (CFAR)</p>
      
    <h4>TCC  - Tororo Child Cohort: Interaction between HIV and malaria in African Children</h4>
    <p><i>Study  period:</i> August 2007  to March 2013. <i>Brief description</i><i>:</i> The study was  designed to; assess whether trimethoprim-sulfamethoxazole(TMP/SMX) prophylaxis is highly  effective in preventing malaria in both HIV-infected and HIV-uninfected  children, assess the effect of TMP/SMX prophylaxis on selection of malaria  parasites containing mutations confering resistance to antifolate  drugs,and  compare the efficacy, safety  and tolerability of artemether-lumefantrine(AL) and  dihydroartemisinin-piperaquine(DP) for the treatment of uncomplicated falciparum  malaria among HIV-infected and uninfected children. The study demonstrated that  TMP/SMX prophylaxis reduced the incidence of malaria by 39% and there was no  difference in prevalence of markers of antifolate resistance in children who  were on TMP/SMX prophylaxis compared to those who were not and that both DP and  AL were equally efficacious and safe for treatment of uncomplicated malaria.<i>Collaborators:</i> MU-UCSF Research  Collaboration. <i> Sponsored by:</i> The Doris Duke Charitable  Foundation, Center for Disease Control (CDC)</p>
    <h4>Access  Bottlenecks Costs and Equity Study </h4>
    <p><i>Study  period:</i>  April 2012 to December 2012. <i>Brief description</i><i>:</i> To understand the constraints to  health service delivery, determinants of patient access and policies which  affect both supply and demand of health care in Uganda. <i>Collaborators:</i> Institute of Health Metrics and Evaluation (IHME). <i>Sponsored by:</i> Bill and Melinda Gates  Foundation</p>
    
    <h4>Serial  HIV Testing Study: Acceptability and Feasibility of Serial HIV Antibody Testing  to Detect Incident HIV Infection during Pregnancy and Lactation and Partner  Testing in Tororo, Uganda</h4>
    <p><i>Study  Period:</i> January 2011  to December 2011. <i>Brief description:</i> To determine the proportion of women who complete serial HIV antibody testing.  The integration of a serial HIV testing program into routine antenatal and  postnatal health care visits was highly acceptable to pregnant women. However,  the majority of women only partially completed the serial testing  protocol.  Thus, a less intensive serial  HIV testing protocol such as 1 repeat test in the 3rd trimester of pregnancy  and 1 repeat test at 6 months postpartum may be more feasible.  <i>Collaborators:</i> MU-UCSF Research Collaboration. <i>Sponsored  by:</i> UCSF Gladstone Institute for Virology and Immunology, Center for AIDS  Research (CFAR)</p>
    
    <h4>A  Programmatic Evaluation of Sulfadoxine-Pyrimethamine for Prevention of  Placental Malaria in Uganda</h4>
    <p> <i>Study  period:</i> February 2011  to July 2011. <i>Brief description:</i> To  determine whether the current program of routine SP administration is effective  in reducing placental malaria in Tororo, Uganda. Findings: In this area of  Uganda with high malaria transmission intensity, use of &gt; 2 doses of SP was  not associated with protection against placental malaria and improved birth  outcomes compared with &lt; 2 doses of SP. These findings highlight the need  for alternatives to SP for the protection against malaria in pregnant women in  areas of moderate-to-high malaria transmission and with widespread SP  resistance<i>. Collaborators:</i> MU-UCSF  Research Collaboration and Uganda Malaria Surveillance Project (USMP). <i>Sponsored by:</i> USMP/CDC<u></u></p>
    
   <h4>Pharmacokinetics  of Piperaquine and Lumefantrine in Young Children in Tororo Uganda</h4>
   <p><i>Study  period:</i> March 2008 to  2012. <i>Brief description:</i> The aim of  this study is to provide information on drug disposition and the relationship  between drug exposure and outcomes.  In  addition, the impact of factors such as weight and concomitant medications on  PK exposure will also be evaluated. <i>Collaborators: </i>MU-UCSF Research Collaboration. <i>Sponsored  by:</i> Novartis, Inc., Holley-Cotec Pharmaceuticals</p>
   
   <h4>PROMOTE:  Prevention of Malaria and HIV Disease in Tororo, Uganda </h4>
      <p> <i>Study  period:</i> <i>October 2009 – July 2013. Brief description: </i>The  PROMOTE program establishes new approaches to reduce HIV and malaria burdens in  sub-Saharan Africa, and enhances the public health approach to both diseases.  Three of the projects are interlinked hypothesis-based intervention cohort  trials. The other 2 projects are linked to all of the clinical trials and  utilize data and specimens from each of these trials to characterize nutrition  and drug resistance. The program is being conducted in Tororo District, Uganda,  a rural area with HIV seroprevalence of 8% and malaria transmission intensity  of 562 infective bites per person year<br>
        <i>Collaborators: </i> MU-UCSF Research Collaboration.  <i>Sponsored  by:</i> The Eunice Kennedy Shriver National Institute of Child Health and Human  Development (NICHD/NIH) </p>
   
      <h4>PROMOTE - Pediatrics</h4>
      <p>A randomized open label trial of HIV  protease inhibitors for the prevention of malaria in HIV-infected children</b> <i>Study  period:</i> October 2009 to January 2013. <i>Brief  description:</i> The aim of this study was to determine if the use of PI-based  (LPV/r) ART versus NNRTI-based ART among HIV-infected children will reduce the  incidence density of malaria in children. This study demonstrated that HIV  infected children treated with LPV/r-based ART regimen had a significantly  lower risk of malaria compared to those treated with an NNRTI-based regimen.</p>
      
      <h4>PROMOTE - PIs (Pregnant women and  Infants): Protease inhibitors to reduce malaria  morbidity in HIV-infected pregnant women</h4>
      <p> <i>Study period: </i>October 2009 to July 2013. <i>Brief description:</i> The aim of this study  is to determine if the use of PI-based ART versus non-PI ART among HIV-infected  pregnant women leads to reduced rates of placental malaria as measured by  Giemsa-stained smear or polymerase chain reaction (PCR) of placental blood.</p>
        
        <h4>PROMOTE – Chemoprevention: A  randomized trial of monthly dihydroartemisinin-piperaquine versus monthly  sulfadoxine-pyrimethamine versus daily trimethoprim-sulfamethoxazole versus no  therapy for the prevention of malaria</h4>
  <p><i>Study period:</i> October 2012 to July 2014. <i>Brief description:</i> The aim of this study  to compare the incidence of malaria among infants enrolled at 4-5 months of age  and randomized to one of the four arms until they reach the age of 24 months.  This study demonstrated that the incidence of malaria was extremely high in the  no chemo-prevention arm despite the use of ITNs and increased with age. In  addition, monthly SP was not effective for the prevention of malaria. In this  study population, daily TS was associated with a modest protection against  malaria, and monthly DP was associated with good protection against malaria.</p>
      
      <h4>PROMOTE  – Drug Resistance: This program includes Pediatrics, PIs and  Chemoprevention</h4>
      <p>  <i>Study  period:</i> October 2012  to July 2013 <i>Brief description:</i> The  aim of this study is to test whether long-term use of chemopreventive  antimalarial therapies in children or of antiretroviral protease inhibitors in  children or pregnant women will decrease the incidence of malaria and related  malarial morbidity. </p>
        
        <h4>PROMOTE - Nutrition</h4>
        <p>Study  period: October 2009 to July 2013. <i>Brief description:</i> This project evaluates the nutritional status of PROMOTE program participants,  identifying factors which increase the risk of nutritional deficiency and  subsequent poor clinical outcomes, correlating levels of malnutrition and ART  pharmacokinetic exposure and response, and pilots a nutritional supplementation  strategy tailored to routine practice in resource limited settings.</p>
 
      <h4>EARLI: Early  Antiretroviral Therapy in Resource Limited Settings in Patients with High CD4+  Cell Counts</h4>
      <p>  <i>Study period: </i>November 2011 to March 2015.<i> Brief description: </i>To assesses efficacy  and adherence to ART, and answer implementation science questions of delivering  ART to high CD4 patients using a streamlined model. Preliminary findings  suggest high ART acceptability among patients with high CD4 counts. <i>Collaborators:</i> MU-UCSF Research  Collaboration, Mbarara University  Joint Program (MJAP), Infectious Diseases Research Collaboration (IDRC). <i>Sponsored by:</i> NIH / Gilead Scineces</p>
      
	    <h4>Supporting the Implementation of  Malaria Prevention and Control Strategies Relevant Ancillary Activities in the  Republic of Uganda</h4>
      <p>  <i>Study period:</i> September 2008 to September 2013. <i>Brief description:</i> The purpose of this  project is to support the implementation of strategies to prevent and control  malaria, and relevant ancillary activities in the Republic of Uganda as part of the President&rsquo;s Malaria Initiative  (PMI). <i>Collaborators:</i> Uganda Malaria  Surveillance Program (UMSP), Uganda National Malaria Control Program, Center  for Disease Control (CDC) <i>Sponsored  by:</i> DHHS/CDC.</p>
      
      <h4>Pharmacokinetic  Interactions between Antiretroviral Agents, Lopinavir/Ritonavir and Efavirenz  and Antimalarial Drug Combinations, Artesunate/ Amodiaquine and  Artemether/Lumefantrine</h4>
      <p><i>Study  period</i>: June 2006 – March 2013. <i>Brief description</i>: This  study includes three (3) components for evaluating potential drug-drug  interactions in healthy HIV sero-negative volunteers. The first component  evaluated the impact of efavirenz on amodiaquine/artesunate but was  discontinued early due to unexpected hepatic toxicity in the first two  subjects.  The second component revealed  that lumefantrine exposure increases 200% in the context of lopinavir/ritonavir  co-administration. However, due to the excellent safety profile for artemether/lumefantrine,  dosage adjustment is not recommended but increased safety monitoring is  warranted.  The third study is nearing  completion and is evaluating the effect of efavirenz on the pharmacokinetics of  artemether/lumefantrine.  It is expected  that efavirenz will lower lumefantrine exposure significantly due to its CYP3A4  induction effects. <i>Collaborators</i>:  MU-UCSF Research Collaboration. <i>Sponsored  by:</i> CFAR, Drug Research Unit, Novartis, Inc.</p>
      
      <h4>HIV VCT and Linkage to Care in Uganda</h4>
      <p><i>Study  Period:</i> September 2007  to August 2012. <i>Brief description:</i> To  compare the efficacy of routine counseling and testing for HIV among  hospitalized adults to traditional counseling and testing in reducing HIV risk  behavior among inpatients after discharge 2) To compare the effectiveness of Enhanced Linkage to Care model of  post-disclosure referral to HIV-specific medical care with Usual Referral in  receipt of opportunistic infection prophylaxis, antiretroviral therapy, and  reducing mortality. <i>Collaborators:</i>  <i>Sponsored  by:</i> NIH (NIMH).</p>
      
  <h4>ACT  PRIME: Comparing the impact of enhanced health facility-based care on malaria  and febrile illnesses in children in Tororo, Uganda</h4>
  <p><i>Study  period:</i> December 2009  to April 2013. The major goals of this study are to compare the impact of  enhanced health facility based care on key population-based indicators,  including the prevalence of anemia in children under five, on key longitudinal  indicators, including treatment incidence density, in a prospectively followed  cohort of children under five and on key indicators of case management for  malaria and other illnesses, including the risk of inappropriate anti-malarial  treatment, in children under five treated at health facilities. <i>Collaborators:</i> Infectious Diseases  Research Collaboration (IDRC), London School of Hygiene and Tropical Medicine  (LSHTM), UCSF. <i>Sponsored by</i>: Bill and  Melinda Gates Foundation. </p>
  
      <h4>ACT  PROCESS </h4>
      <p><i>Study  period:</i> December 2009  to April 2013. <i>Brief description:</i> Involves a comprehensive evaluation framework implemented in parallel with ACT PRIME.  The major goal is to evaluate the process, context and impact of the  intervention implemented in the ACT PRIME study in order to further our  understanding about why the HFI was effective, or not. </p>
      
   <h4>Malaria  Control Policy Assessment - Uganda</h4>
       <p><i>Study  period:</i> March 2012 to  Feb 2014. <i>Brief description:</i> Evaluating the impact of malaria control interventions on child mortality in  Uganda. <i>Collaborators:</i> Infectious  Diseases Research Collaboration (IDRC), University of Washington, Institute for  Health Metrics and Evaluation (IHME). <i>Sponsored  by:</i> Bill and Melinda Gates Foundation.</p>
   
   <h4>TET:  Therapeutic Efficacy Trial- Efficacy of artemether-lumefantrine and amodiaquine  + artesunate for treatment of uncomplicated malaria in children in Uganda </h4>
      <p><i>Study  period:</i> 2013. <i>Brief description:</i> To compare the  efficacy and safety of 2 artemisinin-based combination therapies (ACT),  amodiaquine-artesunate (AQ+AS), and artemether-lumefantrine (AL) for treatment  of uncomplicated malaria in children in Uganda. The study is being conducted at  3 Uganda Malaria Surveillance Project (UMSP), sentinel health centers, Aduku,  Mubende and Kihihi. <i>Collaborators:</i> UMSP, IDRC, MoH, CDC, USAID, PMI, WHO, UCSF. <i>Sponsored by:</i> PMI and WHO.</p>
   
   <h4>R01  Parasitology: Resistance of Malaria Parasites to  Artemisinin-Based Combination Therapies </h4>
      <p><i>Study  period</i>: July 2009 to  June 2014. <i>Brief description:</i> The  study is three fold. 1. To identify genotypes associated with decreased  responses to ACTs in Africa. 2. To assess molecular mechanisms and  parasitological consequences of increasing resistance to ACTs. 3. To  characterize the specific impacts of parasite polymorphisms on drug sensitivity  and fitness. <i>Collaborators: </i>MU-UCSF  Research Collaboration.  <i>Sponsored by:</i> NIH/NIAID.</p>
      <h4>RO1  Immunology: Impact of Chemoprevention on Humoral Antimalarial Immunity </h4>
    <p><i>Study  period:</i> July 2011 to  July 2014. Brief description: To assess the impact of blood stage P. falciparum  infection and chemoprevention on humoral antimalarial immunity. <i>Collaborators:</i> UCSF, IDRC, UC Irvine. <i>Sponsored by:</i> The Doris Duke Charitable  Foundation </p>
    
	  <h4>The PQ Study</h4>
      <p><i>Study period:</i> December 2011 – December 2013. <i>Brief description:</i> An evaluation of the  efficacy and safety of single-dose primaquine for the clearance of gametocytes  in children with uncomplicated malaria in Uganda. The goal of the study is to  evaluate the efficacy and safety of lower doses of primaquine than the dose  (0.75mg primaquine base/kg) recommended in the WHO 2010 malaria treatment  guidelines. <i>Collaborators:</i> Infectious  Diseases Research Collaboration (IDRC), London School of Hygiene and Tropical  Medicine (LSHTM) and the Mahidol Oxford Research Unit (MORU). <i>Sponsored by:</i> Wellcome Trust of Great  Britain, Bill and Melinda Gates Foundation.</p>

<h4>START-ART:  Streamlined ART Initiation Strategy </h4>
    <p><i>Study period:</i> July 2012 to June 2014. <i>Brief description:</i> The project will test  our Streamlined ART Initiation Strategy in a randomized, controlled trial, in  24 clinics in Uganda.The overall  goal of START is to initiate ART among the greatest number of eligible patients  in the shortest amount of time possible while maintaining safety, efficacy and  cost effectiveness. <i>Collaborators:</i> MU-UCSF Research Collaboration.  <i>Sponsored by:</i> National Institute of  Allergy and Infectious Diseases (NIAID). </p>
       
        
    <h4>Tuberculosis Acquisition in Early Childhood in Uganda: Influence of HIV  exposure and malnutrition</h4>
    <p><i>Study  period:</i> February 2013  to February 2014. <i>Brief description:</i> To elucidate the epidemiology of the LTBI reservoir in early childhood and the  influence of HIV-exposure on LTBI and we will test the hypotheses that (1) the  prevalence of LTBI increases with age within the 5 and under age group,  (2) HIV-exposed, un-infected children have a  higher prevalence of LTBI compared to HIV-unexposed children.  In addition to characterizing TB acquisition  in early childhood, we will utilize existing HIV clinical and nutritional data  from established MU-UCSF cohorts to test the hypothesis that HIV-exposed,  un-infected children have an increased risk for LTBI infection relative to  HIV-unexposed children. <i>Collaborators:</i> MU-UCSF Research Collaboration.  <i>Sponsored by:</i> NIAID.</p>

      
</div>
<?php }} ?>